FROM node:20-alpine AS runner
RUN apk add --no-cache openssl
WORKDIR /app

COPY package.json package-lock.json* ./
COPY prisma ./prisma/

RUN npm ci --omit=dev
RUN npx prisma generate

CMD ["sh", "-c", "npx prisma migrate deploy && node prisma/seed.js"]
